server:
  port: 8080

spring:
  application:
    name: GEO-eMall-Master
  profiles:
    active: dev
  #数据库
  datasource:
    name: geoemall
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/geoemall?useUnicode=true&serverTimezone=Asia/Shanghai&characterEncoding=utf8&autoReconnect=true&useSSL=false&allowMultiQueries=true
    username: root
    password: mysql
    hikari:
      minimum-idle: 5 #最小空闲连接
      maximum-pool-size: 15  #最大连接数
      auto-commit: true #自动提交从池中返回的连接
      idle-timeout: 30000 #空闲连接超时时间
      max-lifetime: 30000  #连接最大存活时间
      connection-timeout: 30000 #连接超时时间
      connection-test-query: SELECT 1 #连接测试查询

  # jackson时间格式化
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss

#mybatis
mybatis:
  mapper-locations:
